FROM dvmarques/openjdk-17-jdk-alpine-with-timezone

WORKDIR /app

COPY . .

# # ENTRYPOINT [ "./mvnw", "clean install" ]
# ENTRYPOINT [ "./mvnw", "spring-boot:run" ]


ENTRYPOINT [ "java", "-Dspring.profiles.active=postgres", "org.springframework.boot.loader.launch.JarLauncher" ]